CREATE DATABASE IF NOT EXISTS projetopis;
USE projetopis;

CREATE TABLE IF NOT EXISTS TipoUtilizador (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TipoProfissao (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Pegi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Utilizador (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    tipo INT NOT NULL,
    FOREIGN KEY (tipo) REFERENCES TipoUtilizador(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Pessoa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipo INT NOT NULL,
    photopath VARCHAR(255),
    dataNascimento DATE,
    nacionalidade VARCHAR(255),
    FOREIGN KEY (tipo) REFERENCES TipoProfissao(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Genero (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Filme (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    idPegi INT NOT NULL,
    idDiretorPessoa INT,
    DataLancamento DATETIME NOT NULL,
    tipo ENUM('FILME', 'SERIE') NOT NULL,
    posterPath VARCHAR(255),
    sinopese TEXT,
    duracao INT,
    FOREIGN KEY (idPegi) REFERENCES Pegi(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idDiretorPessoa) REFERENCES Pessoa(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Review (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idUtilizador INT NOT NULL,
    idFilme INT NOT NULL,
    dataReview DATETIME NOT NULL,
    avaliacao TINYINT NOT NULL,
    critica TEXT,
    votosUtilidade INT,
    FOREIGN KEY (idUtilizador) REFERENCES Utilizador(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idFilme) REFERENCES Filme(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Favorito (
    idFilme INT NOT NULL,
    idUtilizador INT NOT NULL,
    PRIMARY KEY(idFilme, idUtilizador),
    FOREIGN KEY (idFilme) REFERENCES Filme(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idUtilizador) REFERENCES Utilizador(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS FilmeGenero (
    idFilme INT NOT NULL,
    idGenero INT NOT NULL,
    PRIMARY KEY(idFilme, idGenero),
    FOREIGN KEY (idFilme) REFERENCES Filme(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idGenero) REFERENCES Genero(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS FilmePessoa (
    idFilme INT NOT NULL,
    idPessoa INT NOT NULL,
    papel TEXT NOT NULL,
    elencoPrincipal BOOLEAN NOT NULL,
    PRIMARY KEY(idFilme, idPessoa),
    FOREIGN KEY (idFilme) REFERENCES Filme(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idPessoa) REFERENCES Pessoa(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO TipoUtilizador (tipo)
VALUES ('normalUser'), ('adminUser');
CREATE TABLE IF NOT EXISTS ReviewUtil (
    idUtilizador INT NOT NULL,
    idReview INT NOT NULL,
    PRIMARY KEY(idUtilizador, idReview),
    FOREIGN KEY (idUtilizador) REFERENCES Utilizador(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idReview) REFERENCES Review(id) ON DELETE CASCADE ON UPDATE CASCADE
);
